function [ W ] = wfromzernikecoef(zernikeNumber)
% returns an expression for a zernike in terms of rho and phi.

% first 36 zernike polynomials, zero basis.
switch zernikeNumber
    case 0 % piston
        W = @(a, rho, phi) a .* ...
            ( 1 ...
            );
    case 1 % tilt x
        W = @(a, rho, phi) a .* ...
            ( rho .* cos(phi) ...
            );
    case 2 % tilt y
        W = @(a, rho, phi) a .* ...
            ( rho .* sin(phi) ...
            );
    case 3 % power / defocus
        W = @(a, rho, phi) a .* ...
            ( 2 .* rho .* rho - 1 ...
            );
    case 4 % astigmatism x
        W = @(a, rho, phi) a .* ...
            ( rho .* rho .* cos(2 * phi) ...
            );
    case 5 % astigmatism y
        W = @(a, rho, phi) a .* ...
            ( rho .* rho .* sin(2 * phi) ...
            );
    case 6 % coma x
        W = @(a, rho, phi) a .* ...
            ( rho .* ...
                ( -2 + 3 .* rho .* rho ) .* cos(phi) ...
            );
    case 7 % coma y
        W = @(a, rho, phi) a .* ...
            ( rho .* ...
                ( -2 + 3 .* rho .* rho ) .* sin(phi) ...
            );
    case 8 % third-order spherical
        W = @(a, rho, phi) a .* ...
            ( - 6 .* rho .* rho + 6 .* rho .^ 4 + 1 ...
            );
    case 9 % trefoil x
        W = @(a, rho, phi) a .* ...
            ( rho .^ 3 .* cos(3 * phi) ...
            );
    case 10 % trefoil y
        W = @(a, rho, phi) a .* ...
            ( rho .^ 3 .* sin(3 * phi) ...
            );
    case 11 % 5th order astigmatism x
        W = @(a, rho, phi) a .* ...
            ( rho .* rho .* ...
                ( -3 + 4 .* rho .* rho ) .* cos(2 * phi) ...
            );
    case 12 % 5th order astigmatism y
        W = @(a, rho, phi) a .* ...
            ( rho .* rho .* ...
                ( -3 + 4 .* rho .* rho ) .* sin(2 * phi) ...
            );
    case 13 % 5th order coma x
        W = @(a, rho, phi) a .* ...
            ( rho .* ...
                ( 3 - 12 .* rho .* rho + 10 .* rho .^ 4 ) ...
                .* cos(phi) ...
            );
    case 14 % 5th order coma y
        W = @(a, rho, phi) a .* ...
            ( rho .* ...
                ( 3 - 12 .* rho .* rho + 10 .* rho .^ 4 ) ...
                .* sin(phi) ...
            );
    case 15 % 5th order spherical
        W = @(a, rho, phi) a .* ...
            ( 12 .* rho .* rho - 30 .* rho .^ 4 + 20.* rho .^ 6 - 1 ...
            );
    case 16 % tetrafoil x
        W = @(a, rho, phi) a .* ...
            ( rho .^ 4 .* cos(4 .* phi) ...
            );
    case 17 % tetrafoil y
        W = @(a, rho, phi) a .* ...
            ( rho .^ 4 .* sin(4 .* phi) ...
            );
    case 18 % 5th order trefoil x
        W = @(a, rho, phi) a .* ...
            ( rho .^ 3 .* (-4 + 5 .* rho .* rho) .* cos(3 .* phi) ...
            );
    case 19 % 5th order trefoil y
        W = @(a, rho, phi) a .* ...
            ( rho .^ 3 .* (-4 + 5 .* rho .* rho) .* cos(3 .* phi) ...
            );
    case 20 % 7th order astigmatism x
        W = @(a, rho, phi) a .* ...
            ( rho .* rho .* (6 - 20 .* rho .* rho + 15 .* rho .^ 4) ...
            .* cos(2 .* phi) ...
            );
    case 21 % 7th order astigmatism y
        W = @(a, rho, phi) a .* ...
            (rho .* rho .* ...
            (6 - 20 .* rho .* rho + 15 .* rho .^ 4) ...
            .* sin(2 .* phi));
    case 22 % 7th order coma x
        W = @(a, rho, phi) a .* ...
            ( rho .* ...
            ( -4 + 30 .* rho .* rho - 60 .* rho .^ 4 + ...
            35 .* rho .^ 6 ) .* ...
            cos(phi) ...
            );
    case 23 % 7th order coma y
        W = @(a, rho, phi) a .* ...
            ( rho .* ...
            ( -4 + 30 .* rho .* rho - 60 .* rho .^ 4 + ...
            35 .* rho .^ 6) .* ...
            sin(phi) ...
            );
    case 24 % 7th order spherical
        W = @(a, rho, phi) a .* ...
            ( -20 .* rho .* rho + 90 .* rho .^ 4 - ...
             140 .* rho .^ 6   + 70 .* rho .^ 8 + 1 ...
            );
    case 25 % pentafoil x
        W = @(a, rho, phi) a .* ...
            ( rho .^ 5 .* cos( 5 .* phi) ...
            );
    case 26 % pentafoil y
        W = @(a, rho, phi) a .* ...
            ( rho .^ 5 .* sin( 5 .* phi) ...
            );
    case 27 % 5th order tetrafoil x
        W = @(a, rho, phi) a .* ...
            ( rho .^ 4 .* ( -5 + 6 .* rho .* rho ) ...
            .* cos( 4 .* phi) ...
            );
    case 28 % 5th order tetrafoil y
        W = @(a, rho, phi) a .* ...
            ( rho .^ 4 .* ( -5 + 6 .* rho .* rho ) ...
            .* sin( 4 .* phi) ...
            );
    case 29 % 7th order trefoil x
        W = @(a, rho, phi) a .* ...
            ( rho .^ 3 .* ...
            ( 10 - 30 .* rho .* rho + 21 .* rho .^ 4) ...
            .* cos(3 .* phi) ...
            );
    case 30 % 7th order trefoil y
        W = @(a, rho, phi) a .* ...
            ( rho .^ 3 .* ...
            ( 10 - 30 .* rho .* rho + 21 .* rho .^ 4) ...
            .* cos(3 .* phi) ...
            );
    case 31 % 9th order astigmatism x
        W = @(a, rho, phi) a .* ...
            ( rho .* rho .* ...
            ( 10 - 30 .* rho .* rho + 21 .* rho .^4 ) .* ...
            cos(2 .* phi) ...
            );
    case 32 % 9th order astigmatism y
        W = @(a, rho, phi) a .* ...
            ( rho .* rho .* ...
            ( 10 - 30 .* rho .* rho + 21 .* rho .^4 ) .* ...
            sin(2 .* phi) ...
            );
    case 33 % 9th order coma x
        W = @(a, rho, phi) a .* ...
            ( rho .* ...
            (5 - 60 .* rho .* rho + 210 .* rho .^ 4 - ...
            280 .* rho .^ 6 + 126 .* rho .^ 8) .* ...
            cos(phi)...
            );
    case 34 % 9th order coma y
        W = @(a, rho, phi) a .* ...
            ( rho .* ...
            (5 - 60 .* rho .* rho + 210 .* rho .^ 4 - ...
            280 .* rho .^ 6 + 126 .* rho .^ 8) .* ...
            sin(phi)...
            );
    case 35 % 9th order spherical
        W = @(a, rho, phi) a .* ...
            (30 .* rho .* rho - ...
            210 .* rho .^ 4 + ...
            560 .* rho .^ 6 - ...
            630 .* rho .^ 8 + ...
            252 .* rho .^ 10 - 1 ...
            );
    otherwise
        error(('Zernike number must be less than or equal to 35.' + ...
               'Fringe zernike terms, beginning at 0.'));
end
end