function [ W ] = wgenerator(aberration)

switch aberration
    % defocus
    case 020
        W = @(a, rho, phi) a .* ...
            ( rho .* rho ...
            );
    % tilt
    case 111
        W = @(a, rho, phi) a .* ...
            ( rho .* cos(phi) ...
            );
    % spherical
    case 040
        W = @(a, rho, phi) a .* ...
            ( rho .^ 4 ...
            );
    % coma
    case 131
        W = @(a, rho, phi) a .* ...
            ( rho .^ 3 .* cos(phi) ...
            );
    % astigmatism
    case 222
        W = @(a, rho, phi) a .* ...
            ( rho .* rho .* cos(phi) .^ 2 ...
            );
    otherwise
        error('see wgenerator.m for valid aberration keys');
end
end
